export const RECIPE_DB = [
  {
    name: '김치찌개', cost: 7000, time: 30, difficulty: '쉬움',
    category: ['건강식'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Kimchi-jjigae.jpg/320px-Kimchi-jjigae.jpg',
    ingredients: ['돼지고기(삼겹살) 150g', '신김치 200g', '두부 150g', '대파 1/2대', '고춧가루 1큰술', '국간장 1큰술', '참기름 1큰술'],
    description: '대표적인 한국 가정식. 신김치와 돼지고기를 넣어 끓인 얼큰한 찌개.',
    steps: ['돼지고기(삼겹살) 150g을 3×3cm 크기로 썬다', '냄비를 중불로 달구고 참기름 1큰술을 두른 뒤 돼지고기를 2분간 볶는다', '신김치 200g을 4cm 길이로 썰어 넣고 함께 2분 더 볶는다', '물 400ml, 고춧가루 1큰술, 국간장 1큰술을 넣고 강불로 끓인다', '끓어오르면 중불로 줄이고 두부 150g을 2cm 크기로 썰어 넣는다', '15분간 보글보글 끓인 후 대파를 어슷썰어 넣는다', '2분 더 끓여 간을 확인한 뒤 완성'],
  },
  {
    name: '된장찌개', cost: 5000, time: 25, difficulty: '쉬움',
    category: ['건강식', '초저가'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Korean.food-Doenjang.jjigae-01.jpg/320px-Korean.food-Doenjang.jjigae-01.jpg',
    ingredients: ['된장 1.5큰술', '두부 100g', '애호박 1/2개', '양파 1/4개', '버섯 50g', '대파 1/2대', '마늘 1큰술', '고추장 0.5큰술'],
    description: '건강한 한국 전통 찌개. 구수한 된장과 각종 채소로 깊은 맛.',
    steps: ['냄비에 물 350ml와 다시마 10g을 넣고 10분간 약불로 우린 뒤 다시마를 건진다', '된장 1.5큰술, 고추장 0.5큰술을 육수에 풀어 넣는다', '중불로 올려 끓이면서 두부 100g을 2cm 주사위 모양으로 썬다', '애호박 1/2개를 반달 모양(1cm 두께)으로 썰어 넣는다', '양파 1/4개(채썰기), 버섯 50g을 넣고 10분간 끓인다', '마늘 1큰술을 넣고 3분 더 끓인다', '대파를 어슷썰어 넣고 불을 끈 뒤 완성'],
  },
  {
    name: '계란볶음밥', cost: 2000, time: 10, difficulty: '쉬움',
    category: ['초저가', '간편요리'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Fried_rice_ham.jpg/320px-Fried_rice_ham.jpg',
    ingredients: ['찬밥 200g', '계란 2개', '대파 1/4대', '간장 1큰술', '참기름 0.5큰술', '식용유 1큰술', '소금 약간'],
    description: '냉장고 재료로 10분 만에 완성하는 빠르고 맛있는 볶음밥.',
    steps: ['대파를 잘게 다진다 (2~3mm 크기)', '팬을 강불로 달구고 식용유 1큰술을 두른다', '계란 2개를 풀어 팬에 붓고 젓가락으로 빠르게 스크램블한다 (30초)', '찬밥 200g을 넣고 주걱으로 누르면서 1~2분간 볶는다', '간장 1큰술을 넣고 30초 더 볶아 고슬고슬하게 만든다', '다진 대파를 넣고 30초 볶은 뒤 참기름 0.5큰술을 둘러 마무리', '소금으로 간을 맞추고 그릇에 담아 완성'],
  },
  {
    name: '제육볶음', cost: 8000, time: 25, difficulty: '쉬움',
    category: ['건강식'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Jeyuk_bokkeum.jpg/320px-Jeyuk_bokkeum.jpg',
    ingredients: ['돼지고기(앞다리살) 200g', '양파 1/2개', '대파 1/2대', '고추장 2큰술', '간장 1큰술', '설탕 1큰술', '다진마늘 1큰술', '참기름 1큰술'],
    description: '매콤달콤한 돼지고기 볶음. 밥 한 공기 순식간에 비우는 반찬.',
    steps: ['고추장 2큰술, 간장 1큰술, 설탕 1큰술, 다진마늘 1큰술, 참기름 1큰술, 생강즙 약간을 섞어 양념장을 만든다', '돼지고기 200g을 0.5cm 두께로 썰어 양념장에 넣고 30분간 재운다', '양파 1/2개는 굵게 채썰고, 대파 1/2대는 어슷썬다', '팬을 강불로 달군 뒤 기름 없이 재운 고기를 넣고 3분간 볶는다', '고기가 반쯤 익으면 양파와 대파를 넣고 2분 더 볶는다', '참기름 약간 두르고 불을 끄면 완성'],
  },
  {
    name: '순두부찌개', cost: 6000, time: 20, difficulty: '쉬움',
    category: ['건강식'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Sundubu-jjigae.jpg/320px-Sundubu-jjigae.jpg',
    ingredients: ['순두부 300g', '계란 1개', '바지락 100g', '고춧가루 2큰술', '대파 1/3대', '마늘 1큰술', '참기름 1큰술', '국간장 1큰술'],
    description: '부드러운 순두부와 바지락의 조화. 얼큰하고 시원한 한국식 찌개.',
    steps: ['냄비에 참기름 1큰술을 두르고 고춧가루 2큰술을 넣어 약불로 1분간 볶아 기름을 낸다', '바지락 100g을 넣고 중불로 1분간 볶는다', '물 300ml와 국간장 1큰술, 다진마늘 1큰술을 넣고 강불로 끓인다', '끓어오르면 순두부 300g을 숟가락으로 크게 떠서 넣는다', '중불로 줄이고 5분간 끓인다', '계란 1개를 깨서 올리고 대파를 어슷썰어 넣는다', '뚜껑 덮고 2분 후 계란이 반숙이 되면 완성'],
  },
  {
    name: '비빔밥', cost: 8000, time: 35, difficulty: '보통',
    category: ['건강식'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Dolsot-bibimbap.jpg/320px-Dolsot-bibimbap.jpg',
    ingredients: ['밥 200g', '시금치 100g', '콩나물 100g', '당근 1/3개', '계란 1개', '고추장 2큰술', '참기름 1큰술', '소금 약간', '식용유'],
    description: '각종 나물과 고추장을 비벼 먹는 영양 가득한 한식. 색감도 아름다운 대표 음식.',
    steps: ['시금치 100g을 끓는 소금물에 1분간 데쳐 찬물에 헹군 뒤 물기를 꼭 짜고 참기름·소금으로 무친다', '콩나물 100g을 뚜껑 덮고 5분간 삶아 물기 빼고 참기름·소금으로 무친다', '당근 1/3개를 곱게 채썰어 소금에 5분 절인 뒤 물기를 짜고 기름 두른 팬에 1분 볶는다', '팬에 기름을 두르고 계란 1개를 반숙 프라이한다', '따뜻한 밥 200g을 그릇에 담고 나물과 프라이를 색깔별로 올린다', '고추장 1~2큰술, 참기름 1큰술을 올리고 취향에 맞게 비빈다'],
  },
  {
    name: '불고기', cost: 9000, time: 30, difficulty: '쉬움',
    category: ['건강식'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Bulgogi.jpg/320px-Bulgogi.jpg',
    ingredients: ['소고기(불고기용) 200g', '양파 1/2개', '대파 1/2대', '간장 3큰술', '설탕 1.5큰술', '참기름 1큰술', '다진마늘 1큰술', '배즙 2큰술'],
    description: '달콤한 간장 양념에 재운 소고기 볶음. 남녀노소 모두 좋아하는 한국 대표 요리.',
    steps: ['간장 3큰술, 설탕 1.5큰술, 참기름 1큰술, 다진마늘 1큰술, 배즙 2큰술, 후추 약간으로 양념장을 만든다', '소고기 200g을 양념장에 넣고 손으로 조물조물 무쳐 30분~1시간 재운다', '양파 1/2개는 굵게 채썰고, 대파 1/2대는 4cm 길이로 썬다', '팬을 중강불로 달구고 기름 없이 양파를 1분 볶는다', '재운 소고기를 넣고 강불로 3~4분 볶는다', '대파를 넣고 1분 더 볶아 완성'],
  },
  {
    name: '라면', cost: 1500, time: 5, difficulty: '쉬움',
    category: ['초저가', '간편요리'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Shin_Ramyun.jpg/320px-Shin_Ramyun.jpg',
    ingredients: ['라면 1개', '계란 1개', '대파 1/4대', '물 550ml'],
    description: '5분이면 완성되는 한국의 국민 음식. 끓이는 방법만 지키면 더 맛있다.',
    steps: ['냄비에 물 550ml를 넣고 강불로 끓인다', '물이 끓으면 스프 먼저 넣고 면을 넣는다', '면을 젓가락으로 풀어주면서 2분간 끓인다', '계란 1개를 깨서 넣고 대파를 어슷썰어 넣는다', '30초 후 불을 끄면 완성 (계란은 완숙이 아닌 반숙 상태가 맛있다)'],
  },
  {
    name: '떡볶이', cost: 4000, time: 20, difficulty: '쉬움',
    category: ['초저가', '간편요리'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Korean_food-Tteokbokki-01.jpg/320px-Korean_food-Tteokbokki-01.jpg',
    ingredients: ['가래떡 200g', '어묵 100g', '고추장 2큰술', '고춧가루 1큰술', '설탕 1큰술', '간장 1큰술', '대파 1/3대', '물 300ml'],
    description: '달콤하고 매콤한 한국의 대표 분식. 쫄깃한 떡과 어묵이 잘 어울린다.',
    steps: ['고추장 2큰술, 고춧가루 1큰술, 설탕 1큰술, 간장 1큰술을 섞어 양념장을 만든다', '어묵 100g을 3×6cm 직사각형으로 썬다', '냄비에 물 300ml와 양념장을 넣고 잘 섞어 중불로 끓인다', '끓어오르면 가래떡 200g과 어묵을 넣는다', '국물을 끼얹으면서 8~10분간 끓인다 (떡이 부드러워질 때까지)', '대파를 어슷썰어 넣고 1분 더 끓여 완성'],
  },
  {
    name: '잡채', cost: 9000, time: 40, difficulty: '보통',
    category: ['건강식'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Japchae.jpg/320px-Japchae.jpg',
    ingredients: ['당면 150g', '소고기 100g', '시금치 80g', '당근 1/3개', '양파 1/2개', '목이버섯 30g', '계란 1개', '간장 3큰술', '참기름 2큰술', '설탕 1큰술'],
    description: '당면과 각종 채소를 버무린 잔칫날 음식. 명절에 빠질 수 없는 한국 전통 요리.',
    steps: ['당면 150g을 끓는 물에 6분간 삶아 찬물에 헹군 뒤 간장 1큰술·참기름 1큰술·설탕 0.5큰술로 미리 버무린다', '소고기 100g을 채썰어 간장 1큰술·설탕 0.5큰술·참기름 0.5큰술로 5분 재운다', '시금치는 데쳐 물기 짜고 소금·참기름으로 무치고, 당근·양파는 채썬다', '목이버섯은 물에 불려 먹기 좋게 뜯는다', '팬에 재운 소고기를 중불로 2~3분 볶고, 이어서 당근·양파·목이버섯을 각각 1~2분씩 볶는다', '계란 지단을 부쳐 채썬다', '큰 볼에 당면과 모든 재료를 넣고 간장·참기름·설탕으로 간하며 버무려 완성'],
  },
  {
    name: '부대찌개', cost: 9000, time: 25, difficulty: '쉬움',
    category: ['간편요리'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Budae-jjigae_by_jetalone_in_Seoul%2C_Korea.jpg/320px-Budae-jjigae_by_jetalone_in_Seoul%2C_Korea.jpg',
    ingredients: ['햄(스팸) 100g', '소시지 100g', '김치 150g', '두부 100g', '라면사리 1개', '고추장 1큰술', '고춧가루 1큰술', '다진마늘 0.5큰술'],
    description: '햄·소시지·김치를 넣어 끓인 얼큰한 찌개. 혼밥에도 완벽한 한 끼.',
    steps: ['햄 100g을 1cm 두께로 썰고 소시지는 어슷썬다', '김치 150g을 4cm 길이로 썰고 두부는 2cm 크기로 썬다', '냄비 바닥에 김치를 깔고 햄·소시지·두부를 올린다', '물 400ml와 고추장 1큰술, 고춧가루 1큰술, 다진마늘 0.5큰술을 넣는다', '강불로 끓이다 끓어오르면 중불로 줄인다', '라면사리를 넣고 3분 더 끓여 면이 익으면 완성'],
  },
  {
    name: '닭볶음탕', cost: 9000, time: 45, difficulty: '보통',
    category: ['건강식'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Dak-bokkeum-tang.jpg/320px-Dak-bokkeum-tang.jpg',
    ingredients: ['닭 1/2마리(500g)', '감자 1개', '당근 1/2개', '양파 1/2개', '고추장 2큰술', '간장 2큰술', '설탕 1큰술', '고춧가루 1큰술', '다진마늘 1큰술'],
    description: '닭과 각종 채소를 매콤한 양념에 조린 한국의 인기 메인 요리.',
    steps: ['닭을 흐르는 물에 깨끗이 씻고 한입 크기로 토막낸다', '끓는 물에 닭을 3분간 데쳐 핏물을 제거하고 건진다', '고추장·간장·설탕·고춧가루·다진마늘·물 3큰술로 양념장을 만든다', '감자·당근을 3cm 크기로 썰고 양파는 굵게 채썬다', '냄비에 닭과 양념장, 물 200ml를 넣고 강불로 끓인다', '끓어오르면 감자·당근을 넣고 중불로 15분 조린다', '양파를 넣고 10분 더 조려 국물이 자작해지면 완성'],
  },
  {
    name: '미역국', cost: 4000, time: 35, difficulty: '쉬움',
    category: ['건강식'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Miyeok-guk.jpg/320px-Miyeok-guk.jpg',
    ingredients: ['건미역 10g', '소고기(국거리) 100g', '간장 1.5큰술', '참기름 1큰술', '다진마늘 0.5큰술', '소금 약간'],
    description: '생일에 먹는 한국 전통 건강 국. 산모와 아이에게도 좋은 영양식.',
    steps: ['건미역 10g을 찬물에 20분간 불려 물기를 짠 뒤 3~4cm 길이로 자른다', '냄비에 참기름 1큰술을 두르고 소고기 100g을 중불로 2분 볶는다', '불린 미역을 넣고 함께 2분 더 볶는다', '물 600ml를 붓고 강불로 끓인다', '끓어오르면 간장 1.5큰술, 다진마늘 0.5큰술을 넣고 중불로 줄인다', '20~25분간 끓여 미역이 부드러워지면 소금으로 간을 맞춰 완성'],
  },
  {
    name: '해물파전', cost: 8000, time: 25, difficulty: '보통',
    category: ['건강식'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Pajeon.jpg/320px-Pajeon.jpg',
    ingredients: ['쪽파 150g', '오징어 100g', '새우 100g', '부침가루 150g', '계란 1개', '물 150ml', '식용유 3큰술'],
    description: '쪽파와 해물로 만든 바삭한 전. 막걸리와 환상의 조합.',
    steps: ['쪽파 150g을 전의 길이에 맞게 자르고, 오징어와 새우를 한입 크기로 썬다', '부침가루 150g, 물 150ml, 계란 1개를 섞어 반죽을 만든다', '팬에 식용유 2큰술을 두르고 중강불로 달군다', '쪽파를 팬에 넓게 펼치고 해물을 올린다', '반죽을 전체적으로 붓고 2~3분간 노릇하게 굽는다', '뒤집개로 조심히 뒤집어 나머지 1큰술 기름 두르고 2분 더 굽는다', '바삭하게 익으면 먹기 좋은 크기로 잘라 완성'],
  },
  {
    name: '김밥', cost: 5000, time: 40, difficulty: '보통',
    category: ['간편요리'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Korean_food-Kimbap-01.jpg/320px-Korean_food-Kimbap-01.jpg',
    ingredients: ['밥 300g', '김 3장', '계란 2개', '시금치 100g', '당근 1/3개', '단무지 3줄', '어묵 50g', '참기름 1.5큰술', '소금 약간'],
    description: '소풍·도시락의 정석. 다양한 재료를 김과 밥으로 감싼 한국식 롤.',
    steps: ['밥에 참기름 1큰술과 소금 약간을 넣어 고루 섞은 뒤 식힌다', '계란 2개를 풀어 소금 넣고 팬에 기름 두르고 얇게 부쳐 채썬다', '시금치를 데쳐 물기 짜고 참기름·소금으로 무치고, 당근을 채썰어 볶는다', '어묵을 채썰어 간장 약간 넣고 1분 볶는다', '김 위에 밥을 얇고 고르게 펴되 위쪽 2cm는 비워둔다', '재료들을 밥 아래쪽에 가지런히 올리고 단단하게 말아준다', '참기름 약간 바르고 1cm 두께로 썰어 완성'],
  },
  {
    name: '두부조림', cost: 4000, time: 20, difficulty: '쉬움',
    category: ['초저가', '건강식'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Dubu-jorim.jpg/320px-Dubu-jorim.jpg',
    ingredients: ['두부 1모(300g)', '간장 2큰술', '고춧가루 1큰술', '다진마늘 0.5큰술', '대파 1/4대', '참기름 0.5큰술', '식용유 2큰술', '설탕 0.5큰술'],
    description: '간장 양념에 노릇하게 조린 두부. 밥 반찬으로 최고인 간편 요리.',
    steps: ['두부 300g을 1.5cm 두께로 썰고 키친타월로 물기를 제거한다', '간장 2큰술, 고춧가루 1큰술, 다진마늘 0.5큰술, 설탕 0.5큰술, 물 2큰술을 섞어 양념장을 만든다', '팬에 식용유 2큰술을 두르고 중강불로 달군다', '두부를 넣고 앞뒤로 각 2~3분씩 노릇노릇하게 굽는다', '양념장을 붓고 약불로 줄여 1~2분간 조린다', '대파를 어슷썰어 올리고 참기름을 뿌려 완성'],
  },
  {
    name: '콩나물국밥', cost: 3000, time: 20, difficulty: '쉬움',
    category: ['초저가', '건강식'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Korean_soup_kongnamul_guk.jpg/320px-Korean_soup_kongnamul_guk.jpg',
    ingredients: ['콩나물 200g', '밥 200g', '대파 1/3대', '새우젓 1큰술', '고춧가루 1큰술', '다진마늘 0.5큰술', '계란 1개'],
    description: '숙취 해소에도 좋은 시원하고 건강한 콩나물국밥.',
    steps: ['콩나물 200g을 깨끗이 씻어 꼬리를 떼어낸다', '냄비에 물 500ml를 넣고 강불로 끓인다', '끓어오르면 콩나물을 넣고 뚜껑을 덮어 5분간 끓인다 (뚜껑을 열면 비린내가 남)', '새우젓 1큰술, 다진마늘 0.5큰술을 넣고 간을 맞춘다', '밥 200g을 넣고 3분 더 끓인다', '계란을 풀어 넣고 대파 어슷썰어 넣는다', '고춧가루를 취향에 맞게 넣어 완성'],
  },
  {
    name: '볶음우동', cost: 5000, time: 15, difficulty: '쉬움',
    category: ['간편요리'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Yaki-udon.jpg/320px-Yaki-udon.jpg',
    ingredients: ['냉동우동면 1개(200g)', '양파 1/4개', '당근 1/4개', '대파 1/3대', '간장 1.5큰술', '굴소스 1큰술', '참기름 0.5큰술', '식용유 1큰술'],
    description: '야채와 우동을 간장 소스에 볶은 간편 한 끼.',
    steps: ['냉동우동면을 전자레인지에 2분 또는 끓는 물에 1분간 데쳐 풀어놓는다', '양파·당근을 채썰고 대파는 어슷썬다', '팬에 식용유 1큰술을 두르고 강불로 달군다', '양파와 당근을 1~2분간 볶는다', '우동면을 넣고 주걱으로 풀면서 2분간 볶는다', '간장 1.5큰술, 굴소스 1큰술을 넣고 30초 더 볶는다', '대파를 넣고 참기름 뿌려 마무리'],
  },
  {
    name: '삼겹살구이', cost: 12000, time: 20, difficulty: '쉬움',
    category: ['건강식'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Samgyeopsal_with_Soju.jpg/320px-Samgyeopsal_with_Soju.jpg',
    ingredients: ['삼겹살 300g', '마늘 10쪽', '쌈채소(상추·깻잎) 100g', '쌈장 2큰술', '소금 약간', '참기름 약간'],
    description: '한국인이 가장 사랑하는 고기 요리. 쌈채소와 쌈장으로 즐기는 별미.',
    steps: ['삼겹살을 냉장고에서 꺼내 15분 상온에 둔다', '그릴 팬을 강불로 5분간 충분히 달군다', '삼겹살을 올리고 앞뒤로 각 3~4분씩 굽는다', '마늘은 통으로 함께 구워 노릇해지면 꺼낸다', '고기를 한입 크기로 자르고 소금·참기름에 찍어 쌈채소에 싸 먹는다', '쌈장을 곁들이면 완성'],
  },
  {
    name: '참치마요덮밥', cost: 3000, time: 10, difficulty: '쉬움',
    category: ['초저가', '간편요리'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Tuna_mayo_rice_bowl.jpg/320px-Tuna_mayo_rice_bowl.jpg',
    ingredients: ['참치캔 1개(150g)', '마요네즈 2큰술', '간장 1큰술', '밥 200g', '구운 김 2장', '참기름 약간', '대파 약간'],
    description: '참치캔과 마요네즈로 10분 만에 완성하는 간편 덮밥.',
    steps: ['참치캔을 열어 기름을 완전히 뺀다 (뚜껑으로 꾹 눌러 짜낸다)', '참치에 마요네즈 2큰술, 간장 1큰술을 넣어 잘 섞는다', '따뜻한 밥 200g을 그릇에 담는다', '참치마요를 밥 위에 올린다', '구운 김을 잘게 잘라 위에 뿌린다', '참기름 약간, 대파 약간을 올려 완성'],
  },
  {
    name: '계란후라이', cost: 1000, time: 5, difficulty: '쉬움',
    category: ['초저가', '간편요리'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Sunny_side_up_eggs.jpg/320px-Sunny_side_up_eggs.jpg',
    ingredients: ['계란 2개', '식용유 1큰술', '소금 약간', '후추 약간'],
    description: '가장 간단한 계란 요리. 흰자는 바삭하고 노른자는 촉촉한 반숙이 최고.',
    steps: ['팬을 중불로 달구고 식용유 1큰술을 두른다', '계란을 조심스럽게 깨서 팬에 넣는다 (높이를 낮춰 깨야 모양이 살아남)', '소금·후추를 뿌린다', '흰자가 완전히 익고 노른자가 반숙이 될 때까지 2~3분 굽는다', '뒤집어 10~15초 익히면 반숙, 1분 더 익히면 완숙 완성'],
  },
  {
    name: '오므라이스', cost: 5000, time: 20, difficulty: '보통',
    category: ['간편요리'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Omurice.jpg/320px-Omurice.jpg',
    ingredients: ['밥 200g', '계란 3개', '양파 1/4개', '케첩 3큰술', '버터 1큰술', '소금·후추 약간'],
    description: '케첩 볶음밥을 계란으로 감싼 부드러운 요리. 아이들이 특히 좋아하는 메뉴.',
    steps: ['양파 1/4개를 잘게 다진다', '팬에 버터 0.5큰술을 녹이고 양파를 2분 볶는다', '밥 200g을 넣고 케첩 2큰술을 넣어 볶음밥을 만든다 (2~3분)', '볶음밥을 그릇에 올려 반원 형태로 만든다', '팬에 버터 0.5큰술을 녹이고 계란 3개를 풀어 소금 넣고 약불로 부친다', '계란이 반숙 상태일 때 볶음밥 위에 조심히 덮는다', '케첩 1큰술을 위에 뿌려 완성'],
  },
  {
    name: '파스타', cost: 7000, time: 25, difficulty: '보통',
    category: ['간편요리'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Spaghetti_bolognese2.jpg/320px-Spaghetti_bolognese2.jpg',
    ingredients: ['파스타면 100g', '베이컨 3줄', '양파 1/4개', '토마토소스 150g', '마늘 3쪽', '올리브유 2큰술', '소금·후추', '파마산 치즈 약간'],
    description: '토마토소스와 베이컨으로 만든 간단한 이탈리안 파스타.',
    steps: ['끓는 물에 소금 1큰술 넣고 파스타면을 봉지 표기 시간보다 1분 적게 삶는다 (알덴테)', '베이컨을 1cm 폭으로 자르고 마늘은 편으로 썬다', '팬에 올리브유 2큰술을 두르고 마늘을 약불로 1분간 볶아 향을 낸다', '베이컨을 넣고 중불로 2분 볶는다', '양파를 채썰어 넣고 1분 볶은 뒤 토마토소스 150g을 넣는다', '면 삶은 물 3큰술을 넣고 소스를 2분 끓인다', '삶은 파스타를 넣고 소스와 잘 섞어 1분 더 볶아 완성'],
  },
  {
    name: '닭갈비', cost: 9000, time: 30, difficulty: '보통',
    category: ['건강식'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Dak-galbi.jpg/320px-Dak-galbi.jpg',
    ingredients: ['닭다리살 300g', '양파 1/2개', '고추장 2큰술', '간장 1큰술', '설탕 1큰술', '고춧가루 1큰술', '다진마늘 1큰술', '참기름 1큰술'],
    description: '매콤한 양념에 볶은 닭고기 요리. 춘천의 명물이자 전국민 인기 메뉴.',
    steps: ['고추장 2큰술, 간장 1큰술, 설탕 1큰술, 고춧가루 1큰술, 다진마늘 1큰술, 생강가루 약간으로 양념장을 만든다', '닭다리살 300g을 한입 크기로 썰어 양념장에 30분 재운다', '양파 1/2개를 굵게 썬다', '팬을 중강불로 달구고 기름을 두른다', '재운 닭고기를 넣고 뚜껑 덮어 5분 익힌다', '뚜껑 열고 양파를 넣어 함께 3분 더 볶는다', '참기름 1큰술 두르고 마무리'],
  },
  {
    name: '수제비', cost: 4000, time: 35, difficulty: '보통',
    category: ['초저가', '건강식'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Sujebi.jpg/320px-Sujebi.jpg',
    ingredients: ['밀가루 200g', '감자 1개', '애호박 1/2개', '대파 1/3대', '멸치 20g', '다시마 10g', '간장 1큰술', '소금 약간'],
    description: '밀가루를 반죽해 뜯어 넣은 얼큰하고 구수한 한국 전통 국수.',
    steps: ['밀가루 200g에 소금 약간, 물 100ml를 넣어 부드럽게 반죽하고 랩 씌워 20분 휴지시킨다', '냄비에 물 1L, 멸치 20g, 다시마 10g을 넣고 10분 끓여 육수를 낸 뒤 건진다', '감자 1개를 1.5cm 크기로 깍뚝썰고, 애호박은 반달 썰기한다', '육수에 간장 1큰술 넣고 강불로 끓이면서 감자를 먼저 넣는다', '5분 후 반죽을 얇게 뜯어 국물에 넣는다 (두께 3~4mm)', '수제비가 떠오르면 애호박 넣고 2분 더 끓인다', '대파 어슷썰어 넣고 소금으로 간해 완성'],
  },
  {
    name: '갈비탕', cost: 12000, time: 90, difficulty: '어려움',
    category: ['건강식'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Galbijjim.jpg/320px-Galbijjim.jpg',
    ingredients: ['소갈비 500g', '무 200g', '대파 1대', '마늘 5쪽', '생강 1쪽', '소금 약간', '후추 약간'],
    description: '진한 사골 육수에 갈비를 넣어 끓인 고급스러운 보양식.',
    steps: ['소갈비 500g을 찬물에 2시간 담가 핏물을 제거한다', '냄비에 갈비를 넣고 물을 가득 부어 강불로 끓인다', '끓어오르면 5분 후 물을 버리고 갈비를 찬물로 씻는다', '깨끗한 냄비에 갈비, 물 2L, 무 200g, 대파 1대, 마늘 5쪽, 생강 1쪽을 넣는다', '강불로 끓이다 약불로 줄여 60~90분간 충분히 끓인다', '무와 파를 건지고 소금·후추로 간을 맞춘다', '그릇에 갈비와 국물을 담아 대파 송송 썰어 올려 완성'],
  },
  {
    name: '잔치국수', cost: 3000, time: 20, difficulty: '쉬움',
    category: ['초저가', '간편요리'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Janchi-guksu.jpg/320px-Janchi-guksu.jpg',
    ingredients: ['소면 100g', '멸치 20g', '다시마 10g', '계란 1개', '대파 1/4대', '간장 2큰술', '소금 약간', '참기름 0.5큰술'],
    description: '잔칫날 먹던 따뜻한 국수. 깔끔한 멸치 육수에 소면을 넣어 만드는 간단한 음식.',
    steps: ['멸치 20g, 다시마 10g을 물 600ml에 넣고 10분 끓여 육수를 내고 건진다', '간장 2큰술, 소금으로 육수 간을 맞춘다', '소면 100g을 끓는 물에 3~4분 삶아 찬물에 헹군다', '계란 1개를 삶거나 지단을 부쳐 채썬다', '그릇에 소면을 담고 뜨거운 육수를 붓는다', '계란 지단과 대파를 얹고 참기름을 뿌려 완성'],
  },
];
